loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: azure
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  ingester:
    chunk_encoding: snappy

  tracing:
    enabled: true

  querier:
    max_concurrent: 4

  storage:
    type: azure
    azure:
      accountName: texasloki
      accountKey: "nVveoKpMWdxfKT4KwKxpgutq8AdhVPBtr1wiLPBEaleLWushVcpsT1zDc3NrV3GkAiEDyyoNUO2M+AStxZ4jmw=="
      connectionString: "DefaultEndpointsProtocol=https;AccountName=texasloki;AccountKey=nVveoKpMWdxfKT4KwKxpgutq8AdhVPBtr1wiLPBEaleLWushVcpsT1zDc3NrV3GkAiEDyyoNUO2M+AStxZ4jmw==;EndpointSuffix=core.windows.net"
      useManagedIdentity: false
      useFederatedToken: false
      userAssignedId: ""  # Si no usas identity asignada, déjalo vacío
      request_timeout: 10s  
      endpointSuffix: core.windows.net

    bucketNames:
      chunks: "chunks"
      ruler: "ruler"
      admin: "admin"

deploymentMode: SimpleScalable

backend:
  replicas: 3
read:
  replicas: 3
write:
  replicas: 3

minio:
  enabled: false
