apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/name: grafana
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        isDefault: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          derivedFields:
            - name: traceID
              matcherRegex: "traceID=(\\w+)"
              url: $${__value.raw}
        secureJsonData:
          httpHeaderValue1: "self-monitoring"
