apiVersion: batch/v1
kind: Job
metadata:
  name: otel-log-test
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: otelcli
          image: ghcr.io/equinix-labs/otel-cli:latest
          command: ["/otel-cli"]
          args:
            - exec
            - "--endpoint=http://otel-collector-opentelemetry-collector.monitoring:4318"
            - "--protocol=http/protobuf"
            - "--name=log-test"
            - "--service=otel-cli-log"
            - "--tp-print"
            - "--verbose"
            - "--attrs=log.severity=INFO,log.message='Log desde otel-cli via exec'"
            - "echo"
            - "Hello"
      restartPolicy: Never
