apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-demo
  template:
    metadata:
      labels:
        app: otel-demo
    spec:
      containers:
        - name: otel-demo
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/demo-client:latest
          args: ["--otlp-endpoint=otel-collector-opentelemetry-collector:4317"]
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector-opentelemetry-collector:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=otel-demo"
          ports:
            - containerPort: 80

