apiVersion: batch/v1
kind: Job
metadata:
  name: otel-test-trace
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: otelcli
          image: ghcr.io/equinix-labs/otel-cli:latest
          command:
            - /otel-cli
          args:
            - exec
            - --endpoint=http://otel-collector-opentelemetry-collector:4318
            - --name=test-span
            - --service=test-otelcli
            - --tp-print
            - --protocol=http/protobuf
            - --verbose
            - echo
            - "Hello OTEL"
      restartPolicy: Never
